"""Validate the register YAML and regenerate register/INVENTORY.md from it.

    python -m pipeline.inventory           # validate + write INVENTORY.md
    python -m pipeline.inventory --check   # validate + fail if INVENTORY.md is stale

Output is deterministic (no timestamps) so --check can run in CI.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict

from .common import REGISTER_DIR, load_backlog, load_register, load_taxonomy

INVENTORY_PATH = REGISTER_DIR / "INVENTORY.md"
REQUIRED = ["id", "law", "citation", "source_url", "agency", "jurisdiction", "applies_to", "tier",
            "behavior_classes", "constraint", "change_source", "provenance", "status"]
REQUIRED_KEYS_NULLABLE = ["provenance_url", "effective_date", "last_checked"]
PROVENANCE = {"salient_stated": "S", "third_party_stated": "T", "added_by_analysis": "A"}
STATUSES = {"verify", "verified"}
CHANGE_SOURCES = {"federal_register", "ecfr", "manual"}
ID_RE = re.compile(r"^[A-Z0-9]+(-[A-Z0-9]+)+$")
JURIS_RE = re.compile(r"^(federal|US-[A-Z]{2})$")


def as_list(v):
    return v if isinstance(v, list) else [v]


def validate_rows(rows: list[dict]) -> list[str]:
    tax = load_taxonomy()
    classes, entities = set(tax["behavior_classes"]), set(tax["covered_entities"])
    errors, seen = [], set()
    for r in rows:
        rid = r.get("id", "<missing id>")
        where = f"{r.get('_file')}:{rid}"
        for k in REQUIRED:
            if r.get(k) in (None, "", []):
                errors.append(f"{where}: missing {k}")
        for k in REQUIRED_KEYS_NULLABLE:
            if k not in r:
                errors.append(f"{where}: key {k} must be present (null allowed)")
        if rid in seen:
            errors.append(f"{where}: duplicate id")
        seen.add(rid)
        if not ID_RE.match(str(rid)):
            errors.append(f"{where}: id must match {ID_RE.pattern}")
        if r.get("source_url") and not str(r["source_url"]).startswith(("https://", "http://")):
            errors.append(f"{where}: source_url must be an http(s) URL")
        if r.get("provenance") not in PROVENANCE:
            errors.append(f"{where}: provenance must be one of {sorted(PROVENANCE)}")
        if r.get("status") not in STATUSES:
            errors.append(f"{where}: status must be one of {sorted(STATUSES)}")
        if r.get("status") == "verified" and not r.get("last_checked"):
            errors.append(f"{where}: status verified requires last_checked")
        if r.get("tier") not in (1, 2):
            errors.append(f"{where}: tier must be 1 or 2")
        if not JURIS_RE.match(str(r.get("jurisdiction"))):
            errors.append(f"{where}: jurisdiction must be 'federal' or US-XX")
        for c in r.get("behavior_classes") or []:
            if c not in classes:
                errors.append(f"{where}: unknown behavior class {c}")
        for e in r.get("applies_to") or []:
            if e not in entities:
                errors.append(f"{where}: unknown applies_to entity {e}")
        srcs = as_list(r.get("change_source") or [])
        for s in srcs:
            if s not in CHANGE_SOURCES:
                errors.append(f"{where}: unknown change_source {s}")
        if "ecfr" in srcs and not r.get("ecfr"):
            errors.append(f"{where}: change_source includes ecfr but no ecfr part given")
    return errors


def _cell(v) -> str:
    return str(v if v is not None else "—").replace("|", "\\|").replace("\n", " ")


def render(rows: list[dict], backlog: list[dict]) -> str:
    tax = load_taxonomy()
    out = [
        "# Register inventory",
        "",
        "<!-- GENERATED by `python -m pipeline.inventory` from register/*.yaml. Do not edit by hand. -->",
        "",
        "Not legal advice. Rows marked `verify` have not been checked against primary text.",
        "",
        "## Summary",
        "",
        f"- Rows: {len(rows)} (Tier 1: {sum(r['tier'] == 1 for r in rows)}, Tier 2: {sum(r['tier'] == 2 for r in rows)})",
        f"- Status: " + ", ".join(f"{s}: {sum(r['status'] == s for r in rows)}" for s in sorted(STATUSES)),
        f"- Provenance: " + ", ".join(f"{PROVENANCE[p]} ({p}): {sum(r['provenance'] == p for r in rows)}" for p in PROVENANCE),
        "- Jurisdictions: " + ", ".join(f"{j}: {n}" for j, n in sorted(
            {j: sum(r['jurisdiction'] == j for r in rows) for j in {r['jurisdiction'] for r in rows}}.items())),
        f"- Open research items (not rows): {len(backlog)}",
        "",
    ]
    for tier, label in ((1, "Tier 1: modeled, triaged, evaluated"), (2, "Tier 2: inventoried and monitored")):
        out += [f"## {label}", "",
                "| ID | Law | Citation | Jurisdiction | Behavior classes | Change source | Prov | Status | Effective |",
                "|---|---|---|---|---|---|---|---|---|"]
        for r in sorted((r for r in rows if r["tier"] == tier), key=lambda r: (r["jurisdiction"] != "federal", r["jurisdiction"], r["id"])):
            out.append("| " + " | ".join([
                f"[{r['id']}]({r['source_url']})", _cell(r["law"]), _cell(r["citation"]), r["jurisdiction"],
                ", ".join(r["behavior_classes"]) + (" (+ all conduct)" if r.get("cross_cutting") else ""),
                " + ".join(as_list(r["change_source"])), PROVENANCE[r["provenance"]], r["status"],
                _cell(r.get("effective_date")),
            ]) + " |")
        out.append("")
    by_class = defaultdict(list)
    for r in rows:
        for c in r["behavior_classes"]:
            by_class[c].append(r["id"])
    out += ["## Coverage by behavior class", "", "| Behavior class | Rows | Count |", "|---|---|---|"]
    for c in tax["behavior_classes"]:
        ids = sorted(by_class.get(c, []))
        out.append(f"| {c} | {', '.join(ids) or '**none**'} | {len(ids)} |")
    out += ["", "## Open research items (state x topic gaps)", "",
            "These have no primary citation yet, so they are not register rows.", "",
            "| Topic | Behavior class | States | Note |", "|---|---|---|---|"]
    for b in backlog:
        out.append(f"| {_cell(b['topic'])} | {b['behavior_class']} | {', '.join(b['states'])} | {_cell(b.get('note') or '')} |")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    rows = load_register()
    errors = validate_rows(rows)
    if errors:
        print("register validation failed:")
        for e in errors:
            print(f"  {e}")
        return 1
    text = render(rows, load_backlog())
    if args.check:
        current = INVENTORY_PATH.read_text() if INVENTORY_PATH.exists() else ""
        if current != text:
            print("register/INVENTORY.md is stale; run `python -m pipeline.inventory`")
            return 1
        print(f"inventory up to date ({len(rows)} rows)")
        return 0
    INVENTORY_PATH.write_text(text)
    print(f"wrote {INVENTORY_PATH.relative_to(REGISTER_DIR.parent)} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
