"""Step 6 - Change records: one markdown file per relevant document in the
review queue (BUILD_SPEC Section 8), plus REVIEW_QUEUE.md indexing everything
awaiting a human. A record whose reviewer sign-off has been filled in is never
overwritten.

records/record_meta.yaml holds what the records add on top of the model's
triage output, which is never edited: links to later or earlier documents
(supersedes / superseded_by). `annotate` applies it to the record files; `run`
calls it after writing records.

    python -m pipeline.records [--data-dir DIR] [--records-dir DIR]
    python -m pipeline.records annotate [--records-dir DIR]   # apply record_meta.yaml only
    python -m pipeline.records check                          # validate record_meta.yaml
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from .common import RECORDS_DIR, data_paths, load_register, read_json, read_jsonl_gz
from .triage import class_tags

STANDARD_QUESTIONS = [
    "Owning config/script: which config, prompt, or script in the deployment implements each affected behavior class? (See adapter/deployment_map.template.yaml.)",
    "Approver: who approves this change (role and name)?",
    "Rollout sequence: what order and timing gets this change in place by the effective date (e.g., staging, pilot portfolio, all portfolios)?",
    "Test evidence required: what test runs or call/transcript samples show compliant behavior before and after rollout?",
]
SIGNED_OFF = re.compile(r"^- Reviewer:[ \t]*\S", re.MULTILINE)
DIFF_LINES_PER_SECTION = 60
META_FILE = "record_meta.yaml"
# How a later document affects the earlier one's record.
RELATION_EFFECT = {
    "withdrawal": "closes",    # guidance or proposal withdrawn or rescinded
    "final_rule": "closes",    # proposal replaced by the final rule (tracked in the final rule's record)
    "disapproval": "closes",   # e.g. Congressional Review Act disapproval
    "vacatur": "reverses",     # court vacatur, or a rule conforming the CFR to one
    "amends": "amends",        # e.g. revised applicability date; record stays open
    "correction": "amends",    # FR correction document
}


def _md_escape(s) -> str:
    return str(s or "").replace("|", "\\|").replace("\n", " ")


def render_record(packet: dict, triage: dict, diff: dict | None, rows_by_id: dict) -> str:
    m = packet["metadata"]
    cfr = ", ".join("{} CFR {}".format(r.get("title"), r.get("part")) for r in (m.get("cfr_references") or []))
    out = [
        f"# Change record: {m.get('document_number')}",
        "",
        "> Generated by servicing-reg-watch. Triage output narrows the queue; it is not legal advice. "
        "Nothing here is effective until a reviewer signs off below.",
        "",
        "## Document",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Document | [{_md_escape(m.get('title'))}]({m.get('html_url')}) |",
        f"| Agency | {_md_escape(', '.join(filter(None, packet.get('agencies', []))))} |",
        f"| Citation | {_md_escape(m.get('citation') or '—')} |",
        f"| CFR references | {_md_escape(cfr) or '—'} |",
        f"| Publication date | {m.get('publication_date')} |",
        f"| Effective date | {triage.get('effective_date') or m.get('effective_on') or 'none stated'} |",
        f"| Change type | {triage['change_type']} |",
        "",
        "## What changed",
        "",
        triage["what_changed"],
        "",
    ]
    if diff and diff.get("sections"):
        out += [f"eCFR section diff (status: `{diff['status']}`):", ""]
        for s in diff["sections"]:
            lines = s["unified_diff"].splitlines()
            shown = lines[:DIFF_LINES_PER_SECTION]
            out += [f"**§ {s['section']}**: {s['change']} "
                    f"(+{s['lines_added']} / -{s['lines_removed']} lines, {s['before_date']} → {s['after_date']})",
                    "", "```diff", *shown, "```"]
            if len(lines) > len(shown):
                out.append(f"_Diff excerpt truncated: {len(lines) - len(shown)} more lines in data/diffs/{m.get('document_number')}.json._")
            out.append("")
    elif diff:
        out += [f"eCFR diff status: `{diff['status']}` (no section text diff available).", ""]
    else:
        out += ["No eCFR diff: the document does not amend a tracked CFR part.", ""]
    out += ["## Affected register rows and behavior classes", ""]
    if triage["affected_register_rows"]:
        out += ["| Row | Law | Citation | Status |", "|---|---|---|---|"]
        for rid in triage["affected_register_rows"]:
            r = rows_by_id.get(rid, {})
            out.append(f"| {rid} | {_md_escape(r.get('law'))} | {_md_escape(r.get('citation'))} | {r.get('status', 'unknown')} |")
    else:
        out.append("No existing register row identified (possible register gap; see open questions).")
    primary, secondary = class_tags(triage)
    out += ["", "Primary behavior classes (drive routing and review): " + (", ".join(f"`{c}`" for c in primary) or "none"),
            "", "Secondary behavior classes (context only): " + (", ".join(f"`{c}`" for c in secondary) or "none"), "",
            "## What a compliant agent must now do", "", triage["compliant_agent_must_now"], "",
            "## Questions the deploying team must answer", ""]
    out += [f"{i}. {q}" for i, q in enumerate(STANDARD_QUESTIONS + triage["open_questions_for_deploying_team"], 1)]
    out += ["", "## Triage", "",
            f"- Relevant: {triage['relevant']}",
            f"- Confidence: {triage['confidence']:.2f}",
            f"- Rationale: {triage['rationale']}",
            "", "## Reviewer sign-off", "",
            "- Decision: [ ] Confirm relevant, implement  [ ] Not relevant, close  [ ] Escalate to counsel",
            "- Reviewer:",
            "- Date:",
            "- Notes:",
            ""]
    return "\n".join(out)


# ------------------------------------------------------- record metadata
def load_record_meta(records_dir: Path | None = None) -> dict:
    path = Path(records_dir or RECORDS_DIR) / META_FILE
    return (yaml.safe_load(path.read_text()) or {}).get("records", {}) if path.exists() else {}


def _link_lines(meta: dict, records_dir: Path) -> list[str]:
    def fmt(link: dict, own_effect: bool) -> str:
        d = link["doc_id"]
        name = f"[{d}]({d}.md)" if (records_dir / f"{d}.md").exists() else d
        effect = RELATION_EFFECT[link["relation"]]
        what = f"{effect} this record" if own_effect else f"{effect} that record"
        note = f"; {link['note']}" if link.get("note") else ""
        return f"  - {name}: {link['relation']} ({what}{note})"
    sup, by = meta.get("supersedes", []), meta.get("superseded_by", [])
    closing = [x for x in by if RELATION_EFFECT[x["relation"]] in ("closes", "reverses")]
    status = ("; ".join(f"{'reversed' if RELATION_EFFECT[x['relation']] == 'reverses' else 'closed'} "
                        f"by {x['doc_id']} ({x['relation']})" for x in closing) if closing else "open")
    out = ["## Supersession", "", f"- Record status: {status}", "- supersedes:" + ("" if sup else " none")]
    out += [fmt(x, False) for x in sup]
    out += ["- superseded_by:" + ("" if by else " none")]
    out += [fmt(x, True) for x in by]
    return out + [""]


def _replace_section(text: str, heading: str, body: list[str], before: str) -> str:
    """Replace the markdown section `heading` (up to the next '## '), or insert it before `before`."""
    block = "\n".join(body)
    pat = re.compile(rf"^{re.escape(heading)}\n.*?(?=^## )", re.MULTILINE | re.DOTALL)
    if pat.search(text):
        return pat.sub(lambda _: block + "\n", text, count=1)
    return text.replace(f"{before}\n", f"{block}\n{before}\n", 1)


def apply_meta(text: str, meta: dict, records_dir: Path) -> str:
    if "supersedes" in meta or "superseded_by" in meta:
        text = _replace_section(text, "## Supersession", _link_lines(meta, records_dir), "## Triage")
    return text


def annotate(records_dir: Path | None = None) -> dict:
    """Apply record_meta.yaml to existing record files. Signed records are left alone."""
    records_dir = Path(records_dir or RECORDS_DIR)
    changed, signed, missing = [], [], []
    for doc_id, meta in load_record_meta(records_dir).items():
        path = records_dir / f"{doc_id}.md"
        if not path.exists():
            missing.append(doc_id)
            continue
        text = path.read_text()
        if SIGNED_OFF.search(text):
            signed.append(doc_id)
            continue
        new = apply_meta(text, meta, records_dir)
        if new != text:
            path.write_text(new)
            changed.append(doc_id)
    return {"annotated": changed, "signed_left_alone": signed, "no_record_file": missing}


def check_meta(records_dir: Path | None = None, store_path: Path | None = None) -> list[str]:
    """Errors in record_meta.yaml: unknown relation, link to a document not in the
    ingested store, or a link not mirrored on the other record when both exist."""
    records_dir = Path(records_dir or RECORDS_DIR)
    meta = load_record_meta(records_dir)
    known = {r["document"]["document_number"] for r in read_jsonl_gz(store_path or data_paths()["fr_store"])}
    errors = []
    for doc_id, m in meta.items():
        for field, mirror in (("supersedes", "superseded_by"), ("superseded_by", "supersedes")):
            for link in m.get(field, []):
                other, rel = link.get("doc_id"), link.get("relation")
                if rel not in RELATION_EFFECT:
                    errors.append(f"{doc_id}: {field} {other}: unknown relation {rel!r}")
                if other not in known:
                    errors.append(f"{doc_id}: {field} {other}: not in the ingested store")
                if other in meta and not any(x["doc_id"] == doc_id and x["relation"] == rel
                                             for x in meta[other].get(mirror, [])):
                    errors.append(f"{doc_id}: {field} {other} ({rel}) not mirrored in {other}.{mirror}")
    return errors


def render_queue_index(review: list[dict], closed_count: int) -> str:
    out = ["# Review queue", "",
           f"{len(review)} documents awaiting human review; {closed_count} auto-closed "
           "(relevant=false, confidence ≥ 0.85; listed in data/queue/auto_closed.json).", "",
           "| Document | Title | Type | Published | Route reason | Relevant | Confidence | Record |",
           "|---|---|---|---|---|---|---|---|"]
    for i in review:
        rec = f"[record]({i['doc_id']}.md)" if i["route_reason"] == "relevant" else "—"
        conf = "—" if i["confidence"] is None else f"{i['confidence']:.2f}"
        rel = "—" if i["relevant"] is None else str(i["relevant"])
        out.append(f"| [{i['doc_id']}]({i['html_url']}) | {_md_escape(i['title'])} | {i['type']} | "
                   f"{i['publication_date']} | {i['route_reason']} | {rel} | {conf} | {rec} |")
    return "\n".join(out) + "\n"


def run(data_dir=None, records_dir: Path | None = None) -> dict:
    paths = data_paths(data_dir)
    records_dir = Path(records_dir or RECORDS_DIR)
    records_dir.mkdir(parents=True, exist_ok=True)
    review = read_json(paths["queue"] / "review_queue.json")
    closed = read_json(paths["queue"] / "auto_closed.json")
    rows_by_id = {r["id"]: r for r in load_register()}
    written, kept_signed = [], []
    for item in review:
        if item["route_reason"] != "relevant":
            continue
        doc_id = item["doc_id"]
        target = records_dir / f"{doc_id}.md"
        if target.exists() and SIGNED_OFF.search(target.read_text()):
            kept_signed.append(doc_id)
            continue
        packet = read_json(paths["triage_inputs"] / f"{doc_id}.json")
        triage = read_json(paths["triage"] / f"{doc_id}.json")
        diff_path = paths["diffs"] / f"{doc_id}.json"
        diff = read_json(diff_path) if diff_path.exists() else None
        target.write_text(render_record(packet, triage, diff, rows_by_id))
        written.append(doc_id)
    (records_dir / "REVIEW_QUEUE.md").write_text(render_queue_index(review, len(closed)))
    return {"records_written": len(written), "signed_records_preserved": kept_signed,
            "annotate": annotate(records_dir)}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", default="run", choices=["run", "annotate", "check"])
    ap.add_argument("--data-dir")
    ap.add_argument("--records-dir")
    args = ap.parse_args(argv)
    if args.command == "annotate":
        print(f"records annotate: {annotate(args.records_dir)}")
    elif args.command == "check":
        errs = check_meta(args.records_dir)
        print(f"record_meta check: {len(errs)} errors")
        for e in errs:
            print(f"  {e}")
        return 1 if errs else 0
    else:
        print(f"records: {run(args.data_dir, args.records_dir)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
