"""Step 6 - Change records: one markdown file per relevant document in the
review queue (BUILD_SPEC Section 8), plus REVIEW_QUEUE.md indexing everything
awaiting a human. A record whose reviewer sign-off has been filled in is never
overwritten.

records/record_meta.yaml holds what the records add on top of the model's
triage output, which is never edited: links to later or earlier documents
(supersedes / superseded_by), the v1.1 change type, v1.1 primary/secondary
behavior classes, and human review overrides (`review`; logged in
records/REVIEW_LOG.md). `annotate` applies it to the record files; `run`
calls it after writing records.

    python -m pipeline.records [--data-dir DIR] [--records-dir DIR]
    python -m pipeline.records annotate [--records-dir DIR]   # apply record_meta.yaml only
    python -m pipeline.records check                          # validate record_meta.yaml
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from .common import (RECORDS_DIR, data_paths, load_product_lines, load_register, load_segments, priority_for,
                     product_lines_for, read_json, read_jsonl_gz, row_segments)
from .triage import class_tags

STANDARD_QUESTIONS = [
    "Owning config/script: which config, prompt, or script in the deployment implements each affected behavior class? (See adapter/deployment_map.template.yaml.)",
    "Approver: who approves this change (role and name)?",
    "Rollout sequence: what order and timing gets this change in place by the effective date (e.g., staging, pilot portfolio, all portfolios)?",
    "Test evidence required: what test runs or call/transcript samples show compliant behavior before and after rollout?",
]
SIGNED_OFF = re.compile(r"^- Reviewer:[ \t]*\S", re.MULTILINE)
DIFF_LINES_PER_SECTION = 60
META_FILE = "record_meta.yaml"
# How a later document affects the earlier one's record.
RELATION_EFFECT = {
    "withdrawal": "closes",    # guidance or proposal withdrawn or rescinded
    "final_rule": "closes",    # proposal replaced by the final rule (tracked in the final rule's record)
    "disapproval": "closes",   # e.g. Congressional Review Act disapproval
    "vacatur": "reverses",     # court vacatur, or a rule conforming the CFR to one
    "amends": "amends",        # e.g. revised applicability date; record stays open
    "correction": "amends",    # FR correction document
}
CONTROL_VALIDATION = ("Control validation: check existing controls against the stated interpretation. "
                      "No agent behavior change unless validation finds a gap.")
INTERPRETATION_NOTE = ("> Change type is `interpretation`: validate existing controls against the text below. "
                       "Change agent behavior only where validation finds a gap.")


def _md_escape(s) -> str:
    return str(s or "").replace("|", "\\|").replace("\n", " ")


def render_record(packet: dict, triage: dict, diff: dict | None, rows_by_id: dict) -> str:
    m = packet["metadata"]
    cfr = ", ".join("{} CFR {}".format(r.get("title"), r.get("part")) for r in (m.get("cfr_references") or []))
    out = [
        f"# Change record: {m.get('document_number')}",
        "",
        "> Generated by servicing-reg-watch. Triage output narrows the queue; it is not legal advice. "
        "Nothing here is effective until a reviewer signs off below.",
        "",
        "## Document",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Document | [{_md_escape(m.get('title'))}]({m.get('html_url')}) |",
        f"| Agency | {_md_escape(', '.join(filter(None, packet.get('agencies', []))))} |",
        f"| Citation | {_md_escape(m.get('citation') or '—')} |",
        f"| CFR references | {_md_escape(cfr) or '—'} |",
        f"| Publication date | {m.get('publication_date')} |",
        f"| Effective date | {triage.get('effective_date') or m.get('effective_on') or 'none stated'} |",
        f"| Change type | {triage['change_type']} |",
        "",
        "## What changed",
        "",
        triage["what_changed"],
        "",
    ]
    if diff and diff.get("sections"):
        out += [f"eCFR section diff (status: `{diff['status']}`):", ""]
        for s in diff["sections"]:
            lines = s["unified_diff"].splitlines()
            shown = lines[:DIFF_LINES_PER_SECTION]
            out += [f"**§ {s['section']}**: {s['change']} "
                    f"(+{s['lines_added']} / -{s['lines_removed']} lines, {s['before_date']} → {s['after_date']})",
                    "", "```diff", *shown, "```"]
            if len(lines) > len(shown):
                out.append(f"_Diff excerpt truncated: {len(lines) - len(shown)} more lines in data/diffs/{m.get('document_number')}.json._")
            out.append("")
    elif diff:
        out += [f"eCFR diff status: `{diff['status']}` (no section text diff available).", ""]
    else:
        out += ["No eCFR diff: the document does not amend a tracked CFR part.", ""]
    out += ["## Affected register rows and behavior classes", ""]
    if triage["affected_register_rows"]:
        out += ["| Row | Law | Citation | Status |", "|---|---|---|---|"]
        for rid in triage["affected_register_rows"]:
            r = rows_by_id.get(rid, {})
            out.append(f"| {rid} | {_md_escape(r.get('law'))} | {_md_escape(r.get('citation'))} | {r.get('status', 'unknown')} |")
    else:
        out.append("No existing register row identified (possible register gap; see open questions).")
    primary, secondary = class_tags(triage)
    out += ["", "Primary behavior classes (drive routing and review): " + (", ".join(f"`{c}`" for c in primary) or "none"),
            "", "Secondary behavior classes (context only): " + (", ".join(f"`{c}`" for c in secondary) or "none"), "",
            "## What a compliant agent must now do", "", triage["compliant_agent_must_now"], "",
            "## Questions the deploying team must answer", ""]
    out += [f"{i}. {q}" for i, q in enumerate(STANDARD_QUESTIONS + triage["open_questions_for_deploying_team"], 1)]
    out += ["", "## Triage", "",
            f"- Relevant: {triage['relevant']}",
            f"- Confidence: {triage['confidence']:.2f}",
            f"- Rationale: {triage['rationale']}",
            "", "## Reviewer sign-off", "",
            "- Decision: [ ] Confirm relevant, implement  [ ] Not relevant, close  [ ] Escalate to counsel",
            "- Reviewer:",
            "- Date:",
            "- Notes:",
            ""]
    return "\n".join(out)


# ------------------------------------------------------- record metadata
def load_record_meta(records_dir: Path | None = None) -> dict:
    path = Path(records_dir or RECORDS_DIR) / META_FILE
    return (yaml.safe_load(path.read_text()) or {}).get("records", {}) if path.exists() else {}


def _link_lines(meta: dict, records_dir: Path) -> list[str]:
    def fmt(link: dict, own_effect: bool) -> str:
        d = link["doc_id"]
        name = f"[{d}]({d}.md)" if (records_dir / f"{d}.md").exists() else d
        effect = RELATION_EFFECT[link["relation"]]
        what = f"{effect} this record" if own_effect else f"{effect} that record"
        note = f"; {link['note']}" if link.get("note") else ""
        return f"  - {name}: {link['relation']} ({what}{note})"
    sup, by = meta.get("supersedes", []), meta.get("superseded_by", [])
    closing = [x for x in by if RELATION_EFFECT[x["relation"]] in ("closes", "reverses")]
    status = ("; ".join(f"{'reversed' if RELATION_EFFECT[x['relation']] == 'reverses' else 'closed'} "
                        f"by {x['doc_id']} ({x['relation']})" for x in closing) if closing else "open")
    out = ["## Supersession", "", f"- Record status: {status}", "- supersedes:" + ("" if sup else " none")]
    out += [fmt(x, False) for x in sup]
    out += ["- superseded_by:" + ("" if by else " none")]
    out += [fmt(x, True) for x in by]
    return out + [""]


def _replace_section(text: str, heading: str, body: list[str], before: str) -> str:
    """Replace the markdown section `heading` (up to the next '## '), or insert it before `before`."""
    block = "\n".join(body)
    pat = re.compile(rf"^{re.escape(heading)}\n.*?(?=^## )", re.MULTILINE | re.DOTALL)
    if pat.search(text):
        return pat.sub(lambda _: block + "\n", text, count=1)
    return text.replace(f"{before}\n", f"{block}\n{before}\n", 1)


_CLASS_LINE = re.compile(r"^(Behavior classes|Primary behavior classes[^:\n]*|Secondary behavior classes[^:\n]*|Tagging note):.*\n\n?",
                         re.MULTILINE)


def _replace_class_lines(text: str, meta: dict) -> str:
    def fmt(cs):
        return ", ".join(f"`{c}`" for c in cs) or "none"
    block = (f"Primary behavior classes (drive routing and review): {fmt(meta.get('behavior_classes_primary', []))}\n\n"
             f"Secondary behavior classes (context only): {fmt(meta.get('behavior_classes_secondary', []))}\n\n")
    if meta.get("tagging_note"):
        block += f"Tagging note: {meta['tagging_note']}\n\n"
    m = _CLASS_LINE.search(text)
    if not m:
        return text
    start = m.start()
    text = _CLASS_LINE.sub("", text)
    return text[:start] + block + text[start:]


def _v1_change_type(doc_id: str) -> str | None:
    path = data_paths()["triage"] / f"{doc_id}.json"
    return read_json(path).get("change_type") if path.exists() else None


def _v1_output(doc_id: str) -> dict | None:
    path = data_paths()["triage"] / f"{doc_id}.json"
    return read_json(path) if path.exists() else None


def _review_lines(review: dict, v1: dict | None) -> list[str]:
    if v1:
        p, s2 = class_tags(v1)
        model = (f"relevant={v1['relevant']}, confidence {v1['confidence']:.2f}, change_type {v1['change_type']}, "
                 f"classes {', '.join(p + s2) or 'none'}")
    else:
        model = "no triage output"
    decision = {"relevant": "relevant: change record created or kept",
                "not_relevant": "not relevant: record closed"}[review["decision"]]
    close = review.get("close")
    if close:
        decision = "relevant as published: change record created, then closed by human review"
    return ["## Human review override", "",
            f"- Model answer (unchanged in data/triage/): {model}",
            f"- Reviewer decision: {decision}",
            f"- Reason: {review['reason']}",
            *([f"- Closed: {close['reason']}"] if close else []),
            f"- Reviewed by {review['reviewer']} on {review['date']}",
            "- Logged in [REVIEW_LOG.md](REVIEW_LOG.md). The v1 eval scores are not affected.", ""]


def _sign_off(text: str, review: dict) -> str:
    box = "- Decision: [ ] Confirm relevant, implement  [x] Not relevant, close  [ ] Escalate to counsel"
    if review.get("close"):  # relevant as published, closed for a stated reason (e.g. rule no longer in force)
        box = "- Decision: [ ] Confirm relevant, implement  [ ] Not relevant, close  [ ] Escalate to counsel  [x] Relevant; closed by review"
        review = {**review, "reason": review["close"]["reason"]}
    text = re.sub(r"^- Decision:.*$", lambda _: box, text, count=1, flags=re.MULTILINE)
    text = re.sub(r"^- Reviewer:[ \t]*$", lambda _: f"- Reviewer: {review['reviewer']}", text, count=1, flags=re.MULTILINE)
    text = re.sub(r"^- Date:[ \t]*$", lambda _: f"- Date: {review['date']}", text, count=1, flags=re.MULTILINE)
    return re.sub(r"^- Notes:[ \t]*$", lambda _: f"- Notes: {review['reason']} (human review override; see REVIEW_LOG.md)",
                  text, count=1, flags=re.MULTILINE)


def override_record(doc_id: str, meta: dict, rows_by_id: dict | None = None) -> str | None:
    """Record for a document the reviewer found relevant against a not-relevant model
    answer. Built from committed metadata; shows the model's answer in its Triage
    section and takes the record fields from the review."""
    from .triage import build_packet
    review, v1 = meta.get("review") or {}, _v1_output(doc_id)
    if review.get("decision") != "relevant" or not review.get("record") or not v1:
        return None
    store = {r["document"]["document_number"]: r["document"] for r in read_jsonl_gz(data_paths()["fr_store"])}
    if doc_id not in store:
        return None
    packet = build_packet(store[doc_id], {}, None, None)
    shown = {**v1, **{k: review["record"][k] for k in ("affected_register_rows", "what_changed", "compliant_agent_must_now",
                                                          "open_questions_for_deploying_team") if k in review["record"]}}
    diff = {"status": "proposed_no_ecfr_change"} if store[doc_id].get("type") == "Proposed Rule" else None
    return render_record(packet, shown, diff, rows_by_id or {r["id"]: r for r in load_register()})


def apply_meta(text: str, meta: dict, records_dir: Path, doc_id: str | None = None) -> str:
    if meta.get("change_type"):
        ct = meta["change_type"]
        v1 = _v1_change_type(doc_id) if doc_id else None
        rows = f"| Change type | {ct}" + (f" (v1 triage output: {v1})" if v1 and v1 != ct else "") + " |"
        if ct == "interpretation":
            rows += f"\n| Required action | {CONTROL_VALIDATION} |"
        if meta.get("change_type_reason"):
            rows += f"\n| Change type basis | {_md_escape(meta['change_type_reason'])} |"
        text = re.sub(r"^\| Change type \|.*\|\n(?:\| (?:Required action|Change type basis) \|.*\|\n)*",
                      lambda _: rows + "\n", text, count=1, flags=re.MULTILINE)
        heading = "## What a compliant agent must now do\n\n"
        text = text.replace(heading + INTERPRETATION_NOTE + "\n\n", heading)
        if ct == "interpretation":
            text = text.replace(heading, heading + INTERPRETATION_NOTE + "\n\n", 1)
    if "behavior_classes_primary" in meta or "behavior_classes_secondary" in meta:
        text = _replace_class_lines(text, meta)
    if "supersedes" in meta or "superseded_by" in meta:
        text = _replace_section(text, "## Supersession", _link_lines(meta, records_dir), "## Triage")
    if meta.get("review"):
        text = _replace_section(text, "## Human review override",
                                _review_lines(meta["review"], _v1_output(doc_id) if doc_id else None), "## Reviewer sign-off")
        if meta["review"]["decision"] == "not_relevant" or meta["review"].get("close"):
            text = _sign_off(text, meta["review"])
    return text


def _patch_queue(records_dir: Path, meta: dict) -> None:
    """Point REVIEW_QUEUE.md rows at the human review outcome."""
    path = records_dir / "REVIEW_QUEUE.md"
    if not path.exists():
        return
    lines = path.read_text().splitlines()
    for i, line in enumerate(lines):
        for doc_id, m in meta.items():
            review = m.get("review")
            if review and line.startswith(f"| [{doc_id}]("):
                cells = line.split(" | ")
                rec = f"[record]({doc_id}.md), " if (records_dir / f"{doc_id}.md").exists() else ""
                outcome = ("relevant, closed" if review.get("close") else "relevant") if review["decision"] == "relevant" \
                    else "not relevant, closed"
                cells[-1] = f"{rec}human review: {outcome} |"
                lines[i] = " | ".join(cells)
    path.write_text("\n".join(lines) + "\n")



# ------------------------------------------------ v1.2 scope: lines, segments, priority
SCOPE_KEY = "v1_2_scope"
SCOPE_LABELS = ("Product lines (v1.2)", "Segments (v1.2)", "Priority (v1.2)")
# Agency fallback for records with no affected register row.
AGENCY_SEGMENTS = {"comptroller-of-the-currency": "bank", "federal-deposit-insurance-corporation": "bank",
                   "federal-reserve-system": "bank", "national-credit-union-administration": "credit_union"}
INDEX_FILES = ("REVIEW_QUEUE.md", "REVIEW_LOG.md", "README.md", "BY_PRODUCT_LINE.md", "BY_SEGMENT.md")


def _store_docs() -> dict:
    return {r["document"]["document_number"]: r["document"] for r in read_jsonl_gz(data_paths()["fr_store"])}


def compute_scope(triage: dict | None, meta: dict, rows_by_id: dict, agencies: list[str], seg_spec: dict) -> dict:
    """Product lines, segments and priority for one record or queue item.

    Classes: the record_meta v1.1 primary/secondary split if present, else the triage
    output. Product lines come from primary classes (from secondary, flagged, when a
    record has no primary class). Segments: union over the affected register rows
    (binds, and unclear where no row binds); with no row, the agency fallback."""
    t = triage or {}
    if "behavior_classes_primary" in meta or "behavior_classes_secondary" in meta:
        primary, secondary = meta.get("behavior_classes_primary", []), meta.get("behavior_classes_secondary", [])
    else:
        primary, secondary = class_tags(t)
    # v1.2 review additions (record_meta `classes_added_by_review`): count toward scope only.
    added = meta.get("classes_added_by_review") or {}
    primary = primary + [c for c in added.get("primary", []) if c not in primary]
    lines, basis = product_lines_for(primary), "primary"
    if not lines and secondary:
        lines, basis = product_lines_for(secondary), "secondary"
    rec = (meta.get("review") or {}).get("record") or {}
    rows = rec.get("affected_register_rows", t.get("affected_register_rows", []))
    binds, unclear = [], []
    for rid in rows:
        if rid in rows_by_id:
            b, u = row_segments(rows_by_id[rid], seg_spec)
            binds += b
            unclear += u
    order = seg_spec["order"]
    source = "register_rows"
    if not rows:
        binds = [AGENCY_SEGMENTS[a] for a in agencies if a in AGENCY_SEGMENTS]
        source = "agency" if binds else "none"
        unclear = [] if binds else list(order)
    binds = [s for s in order if s in set(binds)]
    unclear = [s for s in order if s in set(unclear) and s not in binds]
    return {"product_lines": lines, "product_lines_basis": basis, "segments": binds, "segments_unclear": unclear,
            "segments_source": source, "priority": priority_for(primary)}


def _scope_flow(scope: dict) -> str:
    def lst(v):
        return "[" + ", ".join(v) + "]"
    return ("{" + f"product_lines: {lst(scope['product_lines'])}, product_lines_basis: {scope['product_lines_basis']}, "
            f"segments: {lst(scope['segments'])}, segments_unclear: {lst(scope['segments_unclear'])}, "
            f"segments_source: {scope['segments_source']}, priority: {scope['priority']}" + "}")


def write_scope_meta(records_dir: Path, scopes: dict) -> None:
    """Write each record's computed scope into record_meta.yaml as a one-line
    `v1_2_scope` entry (text edit, so comments and layout are kept). Records not yet
    in the file get an entry appended."""
    path = records_dir / META_FILE
    text = path.read_text() if path.exists() else "records:\n"
    for doc_id, scope in scopes.items():
        line = f"    {SCOPE_KEY}: {_scope_flow(scope)}\n"
        head = re.compile(rf"^  {re.escape(doc_id)}:[ \t]*\n", re.MULTILINE)
        old = re.compile(rf"(^  {re.escape(doc_id)}:[ \t]*\n)    {SCOPE_KEY}: .*\n", re.MULTILINE)
        if old.search(text):
            text = old.sub(lambda m: m.group(1) + line, text, count=1)
        elif head.search(text):
            text = head.sub(lambda m: m.group(0) + line, text, count=1)
        else:
            text = text.rstrip("\n") + f"\n  {doc_id}:\n{line}"
    path.write_text(text)


def _scope_cells(scope: dict) -> tuple[str, str, str]:
    lines = ", ".join(scope["product_lines"]) or "none"
    if scope["product_lines"] and scope["product_lines_basis"] == "secondary":
        lines += " (from secondary classes; no primary class)"
    segs = ", ".join(scope["segments"])
    if scope["segments_unclear"]:
        segs += ("; " if segs else "") + "unclear: " + ", ".join(scope["segments_unclear"])
    segs += {"agency": " (from agency; no register row)", "none": " (no register row)"}.get(scope["segments_source"], "")
    return lines, segs or "none", scope["priority"]


def apply_scope(text: str, scope: dict) -> str:
    """Put the three v1.2 rows at the end of the record's Document table."""
    text = re.sub(r"^\| (?:" + "|".join(re.escape(x) for x in SCOPE_LABELS) + r") \|.*\|\n", "", text, flags=re.MULTILINE)
    rows = "".join(f"| {label} | {_md_escape(v)} |\n" for label, v in zip(SCOPE_LABELS, _scope_cells(scope)))
    m = re.search(r"^## Document\n\n(?:\|.*\|\n)+", text, re.MULTILINE)
    return text[:m.end()] + rows + text[m.end():] if m else text


def record_status(meta: dict, signed: bool) -> str:
    review = meta.get("review") or {}
    if review.get("decision") == "not_relevant":
        return "closed (human review: not relevant)"
    if review.get("close"):
        return "closed (human review: relevant as published; closed)"
    closing = [x for x in meta.get("superseded_by", []) if RELATION_EFFECT[x["relation"]] in ("closes", "reverses")]
    if closing:
        return "; ".join(f"closed by {x['doc_id']} ({x['relation']})" for x in closing)
    return "signed" if signed else "open"


def render_indexes(records_dir: Path, scopes: dict, statuses: dict, titles: dict) -> dict[str, str]:
    pl, seg = load_product_lines(), load_segments()
    pri = {"high": 0, "standard": 1}

    def row(d):
        s = scopes[d]
        lines, segs, _ = _scope_cells(s)
        return (f"| [{d}]({d}.md) | {_md_escape(titles.get(d, ''))} | {s['priority']} | {_md_escape(lines)} | "
                f"{_md_escape(segs)} | {_md_escape(statuses[d])} |")

    head = ["| Record | Title | Priority | Product lines | Segments | Status |", "|---|---|---|---|---|---|"]
    note = ("<!-- GENERATED by `python -m pipeline.records` (v1.2). Do not edit by hand. -->", "",
            f"Priority rule: {pl['priority']['definition']}", "",
            "Values come from `v1_2_scope` in record_meta.yaml. Signed records are not edited; their values appear only "
            "here and in record_meta.yaml.", "")
    by_line = ["# Change records by product line", "", *note]
    for line in pl["order"]:
        ids = sorted((d for d in scopes if line in scopes[d]["product_lines"]), key=lambda d: (pri[scopes[d]["priority"]], d))
        by_line += [f"## {line} ({len(ids)})", "", pl["product_lines"][line]["description"], ""]
        by_line += (head + [row(d) for d in ids]) if ids else ["No records."]
        by_line.append("")
    none = sorted(d for d in scopes if not scopes[d]["product_lines"])
    by_line += [f"## No product line ({len(none)})", "", "Records with no behavior class.", ""]
    by_line += (head + [row(d) for d in none]) if none else ["No records."]
    by_seg = ["# Change records by customer segment", "", *note,
              "A record binds a segment when one of its affected register rows binds it (taxonomy/segments.yaml). "
              "With no affected row, the issuing agency is used where it settles the segment.", ""]
    for s in seg["order"]:
        b = sorted((d for d in scopes if s in scopes[d]["segments"]), key=lambda d: (pri[scopes[d]["priority"]], d))
        u = sorted((d for d in scopes if s in scopes[d]["segments_unclear"]), key=lambda d: (pri[scopes[d]["priority"]], d))
        by_seg += [f"## {s}", "", seg["segments"][s]["description"], "", f"### Binds ({len(b)})", ""]
        by_seg += (head + [row(d) for d in b]) if b else ["No records."]
        by_seg += ["", f"### Unclear ({len(u)})", ""]
        by_seg += (head + [row(d) for d in u]) if u else ["No records."]
        by_seg.append("")
    return {"BY_PRODUCT_LINE.md": "\n".join(by_line).rstrip() + "\n", "BY_SEGMENT.md": "\n".join(by_seg).rstrip() + "\n"}


def record_ids(records_dir: Path) -> list[str]:
    return sorted(p.stem for p in records_dir.glob("*.md") if p.name not in INDEX_FILES)


def scope_all(records_dir: Path) -> dict:
    """Compute scope for every record file, write it to record_meta.yaml, and regenerate the indexes."""
    rows_by_id, seg_spec, store = {r["id"]: r for r in load_register()}, load_segments(), _store_docs()
    meta = load_record_meta(records_dir)
    scopes, statuses, titles = {}, {}, {}
    for d in record_ids(records_dir):
        m = meta.get(d, {})
        doc = store.get(d, {})
        agencies = [a.get("slug") for a in doc.get("agencies", []) if a.get("slug")]
        scopes[d] = compute_scope(_v1_output(d), m, rows_by_id, agencies, seg_spec)
        statuses[d] = record_status(m, bool(SIGNED_OFF.search((records_dir / f"{d}.md").read_text())))
        titles[d] = doc.get("title", "")
    write_scope_meta(records_dir, scopes)
    for name, text in render_indexes(records_dir, scopes, statuses, titles).items():
        (records_dir / name).write_text(text)
    return scopes


def annotate(records_dir: Path | None = None) -> dict:
    """Apply record_meta.yaml to existing record files. Signed records are left alone."""
    records_dir = Path(records_dir or RECORDS_DIR)
    changed, signed, missing, created = [], [], [], []
    all_meta = load_record_meta(records_dir)
    for doc_id, meta in all_meta.items():
        path = records_dir / f"{doc_id}.md"
        if not path.exists():
            text = override_record(doc_id, meta)
            if text is None:
                missing.append(doc_id)
                continue
            path.write_text(text)
            created.append(doc_id)
    scopes = scope_all(records_dir)
    all_meta = load_record_meta(records_dir)
    for doc_id in record_ids(records_dir):
        meta = all_meta.get(doc_id, {})
        path = records_dir / f"{doc_id}.md"
        text = path.read_text()
        if SIGNED_OFF.search(text):
            signed.append(doc_id)
            continue
        new = apply_meta(text, meta, records_dir, doc_id)
        if not SIGNED_OFF.search(new):  # a record signed off (e.g. by a review override) is never given v1.2 rows
            new = apply_scope(new, scopes[doc_id])
        if new != text:
            path.write_text(new)
            changed.append(doc_id)
    _patch_queue(records_dir, all_meta)
    return {"annotated": changed, "created_by_review": created, "signed_left_alone": signed, "no_record_file": missing}


def check_meta(records_dir: Path | None = None, store_path: Path | None = None) -> list[str]:
    """Errors in record_meta.yaml: unknown relation, link to a document not in the
    ingested store, or a link not mirrored on the other record when both exist."""
    records_dir = Path(records_dir or RECORDS_DIR)
    meta = load_record_meta(records_dir)
    known = {r["document"]["document_number"] for r in read_jsonl_gz(store_path or data_paths()["fr_store"])}
    errors = []
    triage_dir = data_paths()["triage"]
    for doc_id, m in meta.items():
        if "behavior_classes_primary" in m or "behavior_classes_secondary" in m:
            p, sec = m.get("behavior_classes_primary", []), m.get("behavior_classes_secondary", [])
            if set(p) & set(sec):
                errors.append(f"{doc_id}: classes in both primary and secondary: {sorted(set(p) & set(sec))}")
            out = triage_dir / f"{doc_id}.json"
            v1 = read_json(out) if out.exists() else None
            # Re-tagging splits the model's classes; it adds and drops none. Review overrides are exempt.
            added = m.get("classes_added_by_review") or {}
            for c in added.get("primary", []):
                if c in set(p) | set(sec):
                    errors.append(f"{doc_id}: class added by review {c} is already tagged")
            if v1 and v1.get("relevant") and not m.get("review") and set(p) | set(sec) != set(class_tags(v1)[0] + class_tags(v1)[1]):
                errors.append(f"{doc_id}: primary + secondary {sorted(set(p) | set(sec))} differ from the triage "
                              f"output's classes {sorted(set(class_tags(v1)[0] + class_tags(v1)[1]))}")
        for field, mirror in (("supersedes", "superseded_by"), ("superseded_by", "supersedes")):
            for link in m.get(field, []):
                other, rel = link.get("doc_id"), link.get("relation")
                if rel not in RELATION_EFFECT:
                    errors.append(f"{doc_id}: {field} {other}: unknown relation {rel!r}")
                if other not in known:
                    errors.append(f"{doc_id}: {field} {other}: not in the ingested store")
                if other in meta and not any(x["doc_id"] == doc_id and x["relation"] == rel
                                             for x in meta[other].get(mirror, [])):
                    errors.append(f"{doc_id}: {field} {other} ({rel}) not mirrored in {other}.{mirror}")
    return errors


def render_queue_index(review: list[dict], closed_count: int, scopes: dict | None = None) -> str:
    """REVIEW_QUEUE.md. v1.2: sorted by priority (high first), then first product line in
    canonical order (items with none last), then the router's order."""
    scopes = scopes or {}
    order = load_product_lines()["order"]

    def key(ix):
        i, item = ix
        s = scopes.get(item["doc_id"]) or {}
        lines = s.get("product_lines") or []
        return (s.get("priority") != "high", order.index(lines[0]) if lines else len(order), i)

    out = ["# Review queue", "",
           f"{len(review)} documents awaiting human review; {closed_count} auto-closed "
           "(relevant=false, confidence ≥ 0.85; listed in data/queue/auto_closed.json).", "",
           "Sorted by priority, then product line (v1.2). Priority rule: taxonomy/product_lines.yaml; "
           "by product line and segment: [BY_PRODUCT_LINE.md](BY_PRODUCT_LINE.md), [BY_SEGMENT.md](BY_SEGMENT.md).", "",
           "| Document | Title | Priority | Product lines | Segments | Type | Published | Route reason | Relevant | Confidence | Record |",
           "|---|---|---|---|---|---|---|---|---|---|---|"]
    for _, i in sorted(enumerate(review), key=key):
        s = scopes.get(i["doc_id"])
        lines, segs, pri = _scope_cells(s) if s else ("—", "—", "—")
        rec = f"[record]({i['doc_id']}.md)" if i["route_reason"] == "relevant" else "—"
        conf = "—" if i["confidence"] is None else f"{i['confidence']:.2f}"
        rel = "—" if i["relevant"] is None else str(i["relevant"])
        out.append(f"| [{i['doc_id']}]({i['html_url']}) | {_md_escape(i['title'])} | {pri} | {_md_escape(lines)} | "
                   f"{_md_escape(segs)} | {i['type']} | {i['publication_date']} | {i['route_reason']} | {rel} | {conf} | {rec} |")
    return "\n".join(out) + "\n"


def queue_scopes(review: list[dict], records_dir: Path) -> dict:
    """Scope per queue item: the record's v1_2_scope, else computed from its triage output."""
    meta = load_record_meta(records_dir)
    rows_by_id, seg_spec, store = {r["id"]: r for r in load_register()}, load_segments(), _store_docs()
    out = {}
    for item in review:
        d = item["doc_id"]
        if SCOPE_KEY in meta.get(d, {}):
            out[d] = meta[d][SCOPE_KEY]
        else:
            agencies = [a.get("slug") for a in store.get(d, {}).get("agencies", []) if a.get("slug")]
            out[d] = compute_scope(_v1_output(d), meta.get(d, {}), rows_by_id, agencies, seg_spec)
    return out


def run(data_dir=None, records_dir: Path | None = None) -> dict:
    paths = data_paths(data_dir)
    records_dir = Path(records_dir or RECORDS_DIR)
    records_dir.mkdir(parents=True, exist_ok=True)
    review = read_json(paths["queue"] / "review_queue.json")
    closed = read_json(paths["queue"] / "auto_closed.json")
    rows_by_id = {r["id"]: r for r in load_register()}
    written, kept_signed = [], []
    for item in review:
        if item["route_reason"] != "relevant":
            continue
        doc_id = item["doc_id"]
        target = records_dir / f"{doc_id}.md"
        if target.exists() and SIGNED_OFF.search(target.read_text()):
            kept_signed.append(doc_id)
            continue
        packet = read_json(paths["triage_inputs"] / f"{doc_id}.json")
        triage = read_json(paths["triage"] / f"{doc_id}.json")
        diff_path = paths["diffs"] / f"{doc_id}.json"
        diff = read_json(diff_path) if diff_path.exists() else None
        target.write_text(render_record(packet, triage, diff, rows_by_id))
        written.append(doc_id)
    ann = annotate(records_dir)
    (records_dir / "REVIEW_QUEUE.md").write_text(render_queue_index(review, len(closed), queue_scopes(review, records_dir)))
    _patch_queue(records_dir, load_record_meta(records_dir))
    return {"records_written": len(written), "signed_records_preserved": kept_signed, "annotate": ann}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", default="run", choices=["run", "annotate", "check"])
    ap.add_argument("--data-dir")
    ap.add_argument("--records-dir")
    args = ap.parse_args(argv)
    if args.command == "annotate":
        print(f"records annotate: {annotate(args.records_dir)}")
    elif args.command == "check":
        errs = check_meta(args.records_dir)
        print(f"record_meta check: {len(errs)} errors")
        for e in errs:
            print(f"  {e}")
        return 1 if errs else 0
    else:
        print(f"records: {run(args.data_dir, args.records_dir)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
