"""Step 6 - Change records: one markdown file per relevant document in the
review queue (BUILD_SPEC Section 8), plus REVIEW_QUEUE.md indexing everything
awaiting a human. A record whose reviewer sign-off has been filled in is never
overwritten.

    python -m pipeline.records [--data-dir DIR] [--records-dir DIR]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from .common import RECORDS_DIR, data_paths, load_register, read_json

STANDARD_QUESTIONS = [
    "Owning config/script: which config, prompt, or script in the deployment implements each affected behavior class? (See adapter/deployment_map.template.yaml.)",
    "Approver: who approves this change (role and name)?",
    "Rollout sequence: what order and timing gets this change in place by the effective date (e.g., staging, pilot portfolio, all portfolios)?",
    "Test evidence required: what test runs or call/transcript samples show compliant behavior before and after rollout?",
]
SIGNED_OFF = re.compile(r"^- Reviewer:[ \t]*\S", re.MULTILINE)
DIFF_LINES_PER_SECTION = 60


def _md_escape(s) -> str:
    return str(s or "").replace("|", "\\|").replace("\n", " ")


def render_record(packet: dict, triage: dict, diff: dict | None, rows_by_id: dict) -> str:
    m = packet["metadata"]
    cfr = ", ".join("{} CFR {}".format(r.get("title"), r.get("part")) for r in (m.get("cfr_references") or []))
    out = [
        f"# Change record: {m.get('document_number')}",
        "",
        "> Generated by servicing-reg-watch. Triage output narrows the queue; it is not legal advice. "
        "Nothing here is effective until a reviewer signs off below.",
        "",
        "## Document",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Document | [{_md_escape(m.get('title'))}]({m.get('html_url')}) |",
        f"| Agency | {_md_escape(', '.join(filter(None, packet.get('agencies', []))))} |",
        f"| Citation | {_md_escape(m.get('citation') or '—')} |",
        f"| CFR references | {_md_escape(cfr) or '—'} |",
        f"| Publication date | {m.get('publication_date')} |",
        f"| Effective date | {triage.get('effective_date') or m.get('effective_on') or 'none stated'} |",
        f"| Change type | {triage['change_type']} |",
        "",
        "## What changed",
        "",
        triage["what_changed"],
        "",
    ]
    if diff and diff.get("sections"):
        out += [f"eCFR section diff (status: `{diff['status']}`):", ""]
        for s in diff["sections"]:
            lines = s["unified_diff"].splitlines()
            shown = lines[:DIFF_LINES_PER_SECTION]
            out += [f"**§ {s['section']}**: {s['change']} "
                    f"(+{s['lines_added']} / -{s['lines_removed']} lines, {s['before_date']} → {s['after_date']})",
                    "", "```diff", *shown, "```"]
            if len(lines) > len(shown):
                out.append(f"_Diff excerpt truncated: {len(lines) - len(shown)} more lines in data/diffs/{m.get('document_number')}.json._")
            out.append("")
    elif diff:
        out += [f"eCFR diff status: `{diff['status']}` (no section text diff available).", ""]
    else:
        out += ["No eCFR diff: the document does not amend a tracked CFR part.", ""]
    out += ["## Affected register rows and behavior classes", ""]
    if triage["affected_register_rows"]:
        out += ["| Row | Law | Citation | Status |", "|---|---|---|---|"]
        for rid in triage["affected_register_rows"]:
            r = rows_by_id.get(rid, {})
            out.append(f"| {rid} | {_md_escape(r.get('law'))} | {_md_escape(r.get('citation'))} | {r.get('status', 'unknown')} |")
    else:
        out.append("No existing register row identified (possible register gap; see open questions).")
    out += ["", "Behavior classes: " + (", ".join(f"`{c}`" for c in triage["behavior_classes"]) or "none"), "",
            "## What a compliant agent must now do", "", triage["compliant_agent_must_now"], "",
            "## Questions the deploying team must answer", ""]
    out += [f"{i}. {q}" for i, q in enumerate(STANDARD_QUESTIONS + triage["open_questions_for_deploying_team"], 1)]
    out += ["", "## Triage", "",
            f"- Relevant: {triage['relevant']}",
            f"- Confidence: {triage['confidence']:.2f}",
            f"- Rationale: {triage['rationale']}",
            "", "## Reviewer sign-off", "",
            "- Decision: [ ] Confirm relevant, implement  [ ] Not relevant, close  [ ] Escalate to counsel",
            "- Reviewer:",
            "- Date:",
            "- Notes:",
            ""]
    return "\n".join(out)


def render_queue_index(review: list[dict], closed_count: int) -> str:
    out = ["# Review queue", "",
           f"{len(review)} documents awaiting human review; {closed_count} auto-closed "
           "(relevant=false, confidence ≥ 0.85; listed in data/queue/auto_closed.json).", "",
           "| Document | Title | Type | Published | Route reason | Relevant | Confidence | Record |",
           "|---|---|---|---|---|---|---|---|"]
    for i in review:
        rec = f"[record]({i['doc_id']}.md)" if i["route_reason"] == "relevant" else "—"
        conf = "—" if i["confidence"] is None else f"{i['confidence']:.2f}"
        rel = "—" if i["relevant"] is None else str(i["relevant"])
        out.append(f"| [{i['doc_id']}]({i['html_url']}) | {_md_escape(i['title'])} | {i['type']} | "
                   f"{i['publication_date']} | {i['route_reason']} | {rel} | {conf} | {rec} |")
    return "\n".join(out) + "\n"


def run(data_dir=None, records_dir: Path | None = None) -> dict:
    paths = data_paths(data_dir)
    records_dir = Path(records_dir or RECORDS_DIR)
    records_dir.mkdir(parents=True, exist_ok=True)
    review = read_json(paths["queue"] / "review_queue.json")
    closed = read_json(paths["queue"] / "auto_closed.json")
    rows_by_id = {r["id"]: r for r in load_register()}
    written, kept_signed = [], []
    for item in review:
        if item["route_reason"] != "relevant":
            continue
        doc_id = item["doc_id"]
        target = records_dir / f"{doc_id}.md"
        if target.exists() and SIGNED_OFF.search(target.read_text()):
            kept_signed.append(doc_id)
            continue
        packet = read_json(paths["triage_inputs"] / f"{doc_id}.json")
        triage = read_json(paths["triage"] / f"{doc_id}.json")
        diff_path = paths["diffs"] / f"{doc_id}.json"
        diff = read_json(diff_path) if diff_path.exists() else None
        target.write_text(render_record(packet, triage, diff, rows_by_id))
        written.append(doc_id)
    (records_dir / "REVIEW_QUEUE.md").write_text(render_queue_index(review, len(closed)))
    return {"records_written": len(written), "signed_records_preserved": kept_signed}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-dir")
    ap.add_argument("--records-dir")
    args = ap.parse_args(argv)
    print(f"records: {run(args.data_dir, args.records_dir)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
